language: java
jdk: oraclejdk11
#install: true
#script: mvn clean install
dist: trusty
sudo: false
addons:
  ssh_known_hosts:
  - "192.119.116.101"
services:
  - docker
before_install:
- openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv
  -in .travis/deploy_rsa.enc -out .travis/id_rsa -d
- eval "$(ssh-agent -s)"
- cp .travis/id_rsa ~/.ssh/deploy_rsa
- chmod 600 ~/.ssh/deploy_rsa
- ssh-add ~/.ssh/deploy_rsa
- docker build -t kalix/marketdata marketdata
- docker build -t kalix/matchingengine matchingengine

deploy:
- provider: script
  skip_cleanup: true
  script: bash .travis/deploy.sh
  verbose: true
  on:
    branch: main
#    all_branches: true
cache:
  directories:
  - "$HOME/.m2"
