version: "3.9"

services:
  watchtower:
    command: --label-enable --cleanup --interval 300
    image: containrrr/watchtower
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    network_mode: none
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  femd:
    hostname: femd
    image: kalix/femd:v1
    depends_on:
      - watchtower
    ports:
      - "9880:9880"
#    volumes:
#      - db_data:/var/lib/mysql
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    restart: always
#    environment:
#      MYSQL_ROOT_PASSWORD: somewordpress
#      MYSQL_DATABASE: wordpress
#      MYSQL_USER: wordpress
#      MYSQL_PASSWORD: wordpress

  feme:
    hostname: feme
    depends_on:
      - femd
      - watchtower
    image: kalix/feme:v1
    ports:
      - "8323:8323"
    links:
      - femd
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
#    network_mode: "host"
#    extra_hosts: # <---- here
#      - localhost:192.168.1.38

#    environment:
#      WORDPRESS_DB_HOST: db:3306
#      WORDPRESS_DB_USER: wordpress
#      WORDPRESS_DB_PASSWORD: wordpress
#      WORDPRESS_DB_NAME: wordpress
#volumes:
#  db_data: {}